src/components/breadcrumb/index.js
src/components/checkbox/index.js
src/components/checkbox/stories.js
src/components/fileUpload/index.js
src/components/inputField/index.js
src/components/layout/index.js
src/components/radio/index.js
src/components/radio/test.js
src/components/select/index.js
src/components/textarea/index.js

- removed the spread operator and added the particular props

destructured constructors

---

src/components/errorText/index.js
src/components/errorText/stories.js
src/components/errorText/test.js
src/components/fileUpload/index.js
src/components/hintText/index.js
src/components/hintText/stories.js
src/components/hintText/test.js
src/components/input/index.js
src/components/input/stories.js
src/components/input/test.js
src/components/inputField/index.js
src/components/label/index.js
src/components/label/stories.js
src/components/label/test.js
src/components/labelText/index.js
src/components/labelText/stories.js
src/components/labelText/test.js
src/components/select/index.js
src/components/textarea/index.js
src/constants/index.js
src/stories/index.js

- moved the some of the styling into constants file so it can be reused across other components
- created new smaller components; label, labelText, hintText, errorText, input
- refactored the components with reusable smaller components

DRYing out some of the styling

---

src/components/checkbox/index.js
src/components/radio/index.js

- fixed additional props (disabled & pre-selected)
Merge branch 'master' into feature/dryStyling

added defaultChecked & disabled to Radio & Checkbox

---

src/components/dateInput/index.js
src/components/errorText/index.js
src/components/fileUpload/index.js
src/components/hintText/index.js
src/components/input/index.js
src/components/label/index.js
src/components/labelText/index.js
src/components/select/index.js
src/components/textarea/index.js

Some places the comment ref was copied and pasta'd, and some weren't that relevant.
Updated their appropriate reference.

updated comment references

---

package-lock.json
src/stories/index.js

- missing Panel from stories index
* [ NA ] Documentation
* [ NA ] Tests
* [ YES ] Ready to be merged

panel missing from the stories index

---

package-lock.json
package.json

Specify peerDependencies rather than dependencies to ensure using same version as parent.

peerDependencies

---

package-lock.json
package.json
scripts/test.js
src/components/BackLink/__snapshots__/test.js.snap
src/components/Breadcrumb/__snapshots__/test.js.snap
src/components/Button/__snapshots__/test.js.snap
src/components/Checkbox/__snapshots__/test.js.snap
src/components/DateInput/__snapshots__/test.js.snap
src/components/ErrorText/__snapshots__/test.js.snap
src/components/FileUpload/__snapshots__/test.js.snap
src/components/HintText/__snapshots__/test.js.snap
src/components/Input/__snapshots__/test.js.snap
src/components/InputField/__snapshots__/test.js.snap
src/components/Label/__snapshots__/test.js.snap
src/components/LabelText/__snapshots__/test.js.snap
src/components/Layout/__snapshots__/test.js.snap
src/components/Panel/__snapshots__/test.js.snap
src/components/Radio/__snapshots__/test.js.snap
src/components/Select/__snapshots__/test.js.snap
src/components/TextArea/__snapshots__/test.js.snap

eject create react app as we were only using it for running unit tests

eject create react app and only keep jest/test script

---

src/index.js

added gridRow and gridCol components to export

added grid components to export

---

src/components/Checkbox/__snapshots__/test.js.snap
src/components/Checkbox/index.js
src/components/DateInput/__snapshots__/test.js.snap
src/components/FileUpload/__snapshots__/test.js.snap
src/components/GridCol/index.js
src/components/InputField/__snapshots__/test.js.snap
src/components/Label/__snapshots__/test.js.snap
src/components/Label/index.js
src/components/Select/__snapshots__/test.js.snap
src/components/Select/index.js
src/components/TextArea/__snapshots__/test.js.snap

- added select component
- added checkbox

update more components with props for FF

---

src/components/Checkbox/__snapshots__/test.js.snap
src/components/Checkbox/index.js
src/components/GridCol/index.js
src/components/Layout/__snapshots__/test.js.snap
src/components/Layout/index.js

- fixed label styling (so labels dont stretch across white space)
- fixed default column styling (multiple columns on mobile were adding unnecessary padding)
- fixed layout padding issue (page was clipping on 320px width)

fixed label styling, fixed default column styling, fixed layout padding

---

.gitignore
.npmignore
.travis.yml
package-lock.json
package.json

- track bundle size in PRs
- ensure lib and vendor bundles don't go above 50kb each

Bundle size

---

package.json
src/components/BackLink/__snapshots__/test.js.snap
src/components/Breadcrumb/__snapshots__/test.js.snap
src/components/Button/__snapshots__/test.js.snap
src/components/Checkbox/__snapshots__/test.js.snap
src/components/DateInput/__snapshots__/test.js.snap
src/components/ErrorText/__snapshots__/test.js.snap
src/components/FileUpload/__snapshots__/test.js.snap
src/components/HintText/__snapshots__/test.js.snap
src/components/Input/__snapshots__/test.js.snap
src/components/InputField/__snapshots__/test.js.snap
src/components/Label/__snapshots__/test.js.snap
src/components/LabelText/__snapshots__/test.js.snap
src/components/Layout/__snapshots__/test.js.snap
src/components/Panel/__snapshots__/test.js.snap
src/components/Radio/__snapshots__/test.js.snap
src/components/Select/__snapshots__/test.js.snap
src/components/TextArea/__snapshots__/test.js.snap

Implement jest-glamor-react

---

.storybook/addons.js
package-lock.json
package.json
src/components/Button/stories.js

- added knob example to buttons
- added storybook knobs

example of knobs in storybook

---

scripts/createComponent.js

- changed the first character of the module to be uppercase, to meet eslint expectations

fixed module to start with uppercase

---

.drone.yml

Basic Drone CI config.
This will be used if/when we move to using https://github.com/UKHomeOffice/govuk-react

add basic drone config

---

src/components/Breadcrumb/stories.js
src/components/Button/__snapshots__/test.js.snap
src/components/Button/index.js
src/components/PhaseBanner/stories.js

- added asAnchor to components that used native anchor tag
- added font family to button

added asAnchor to existing components

---

API.md
src/index.js

- exported missing components 
- updated doc.md

exported missing components

---

README.md

improve readme to represent new monorepo structure

improve readme to represent new monorepo structure

---

packages/constants/src/test.js

unit tests for constants exports

unit tests for constants exports

---

.gitignore
packages/hoc/src/asAnchor/__snapshots__/test.js.snap
packages/hoc/src/asAnchor/index.js

- removed glamorous wrapper
- styled the HOC
- added components/*/node_modules to .gitignore

styled hoc and removed wrapper

---

scripts/createComponent.js

- changed paths/folder structure to suit new format
- added package.json file
- changed templates to suit linting (quotes, comma dangle)

amended createComponent to work with monorepo

---

components/list-item/src/index.js
components/list-navigation/src/__snapshots__/test.js.snap
components/ordered-list/package.json
components/ordered-list/src/__snapshots__/test.js.snap
components/ordered-list/src/example.js
components/ordered-list/src/index.js
components/ordered-list/src/stories.js
components/ordered-list/src/test.js
components/unordered-list/src/__snapshots__/test.js.snap
components/unordered-list/src/index.js
components/unordered-list/src/stories.js
components/unordered-list/src/test.js
package-lock.json
package.json
packages/storybook/src/stories/index.js
scripts/createComponent.js
yarn.lock

Fixes #110 
New component `ordered-list`
---
Fixed `unordered-list` padding, #110
before:
after:

added ordered list, fixed unordered list padding (fixes #110)

---

package.json
packages/api-docs/src/index.js

api-docs cli should resolve files relative to cwd, not src file

api-docs cli should resolve files relative to cwd, not src file

---

CONTRIBUTING.md

notes on PR in contributing.md

---

.travis.yml
CONTRIBUTING.md
scripts/release.sh

Creating a shell script to run to prepare a release, and updated docs

release script

---

components/text-area/src/index.js

Export TextAreaField as well as TextArea

Export TextAreaField as well as TextArea

---

CONTRIBUTING.md

A couple of extra notes about release process

Release process update

---

CONTRIBUTING.md

updated the contributing with missing steps

added missing steps from contrib

---

components/loading-box/src/__snapshots__/test.js.snap
components/loading-box/src/index.js
components/loading-box/src/stories.js
yarn.lock

- added min height 100px
- changed default opacity to .85
- showed Storybook example
- updated snapshot
fixex #198

Minimum height for loading box

---

components/loading-box/package-lock.json
components/loading-box/package.json
components/loading-box/src/__snapshots__/test.js.snap
components/loading-box/src/index.js
components/loading-box/src/stories.js
components/loading-box/src/test.js
components/search-box/src/index.js
components/select/src/index.js
components/text-area/src/index.js

fixes #199 
- added label next or below the spinner
- passes label prop to spinner

pass text to loading spinner

---

components/loading-box/src/__snapshots__/test.js.snap
components/loading-box/src/index.js

- added will-change attribute to tell browser what the element is going to do

added will-change to loading box

---

packages/icons/package.json
packages/icons/src/SVGBase/index.js
packages/icons/src/index.js

export svgbase so it can be used by other projects

export svgbase so it can be used by other projects

---

package.json
packages/storybook/package.json

Add top-nav to root and storybook dependancies

---

components/main/README.md
components/main/package.json
components/main/src/__snapshots__/test.js.snap
components/main/src/index.js
components/main/src/stories.js
components/main/src/test.js
package.json
packages/govuk-react/package.json
packages/govuk-react/src/index.js
packages/storybook/package.json

**Checklist**:
It might be ready to be merged, but could do with a review if possiblé

Add Main component with tests and story

---

components/main/src/__snapshots__/test.js.snap
components/main/src/test.js

Add expect to test and update snapshot

---

components/panel/src/index.js
components/panel/src/test.js

Fix console error for arrays passed to panel body

---

components/date-input/src/__snapshots__/test.js.snap
components/error-summary/src/__snapshots__/test.js.snap
components/file-upload/src/__snapshots__/test.js.snap
components/input-field/src/__snapshots__/test.js.snap
components/label/src/__snapshots__/test.js.snap
components/label/src/index.js
components/select/src/__snapshots__/test.js.snap
components/text-area/src/__snapshots__/test.js.snap

Need to remove 100% width from label as this is effecting the styling of other components implemented eg; cropping a select dropdown when it is side by side.

Remove width from label component

---

components/error-summary/src/__snapshots__/test.js.snap
components/error-summary/src/index.js
packages/hoc/src/withWhiteSpace/__snapshots__/test.js.snap

**Checklist**:
* [ x ] Documentation
* [ x ] Tests
* [ x ] Ready to be merged

Header from H2 -> H3 in error summary page

---

.babelrc.js

Solves #384 (as per comments at https://github.com/stevesims/govuk-frederic/pull/66)
**Checklist**:

Have Babel strip propTypes

---

packages/govuk-react/package.json

Addresses https://github.com/UKHomeOffice/govuk-react/issues/297
**Checklist**:

Add emotion & react-emotion to peerDeps

---

.travis.yml

reenable chromatic

---

.eslintrc.js
packages/storybook-components/.eslintrc.js
packages/storybook-components/src/ReadMeHidePreview.js
packages/storybook-components/src/WithDocsCustom.js
packages/storybook/.eslintrc.js
packages/storybook/src/stories/index.js

Exempt component docs for Chromatic userAgent

---

README.md

Update readme urls to account for org change

---

components/paragraph/src/__snapshots__/test.js.snap
components/paragraph/src/test.js

Bring Paragraph test coverage to 100%

---

.travis.yml
package.json
yarn.lock

add codacy coverage to CI

---

components/multi-choice/src/__snapshots__/test.js.snap
components/multi-choice/src/fixtures.js
components/multi-choice/src/stories.js
components/multi-choice/src/test.js

Also re-wrote tests to be more explicit and to no longer send in unexpected `error` prop.
When this and the [Paragraph test](https://github.com/UKHomeOffice/govuk-react/pull/396) are merged it'll bring govuk-react coverage to 100%.
**Checklist**:

Bring MultiChoice test coverage to 100%

---

README.md
components/date-input/README.md

Adds a message about Chromaticqa to our readme - it really is awesome, so I hope the wording is appropriate : )

Add Chromaticqa attribution

---

components/grid-col/src/__snapshots__/test.js.snap
components/grid-col/src/index.js
components/grid-col/src/stories.js
components/grid-col/src/test.js
components/grid-row/src/__snapshots__/test.js.snap
components/grid-row/src/index.js
components/grid-row/src/stories.js

Fixes #432
Ensures that fixed width `GridCol` elements get `flex-shrink: 0` set
**Checklist**:

Make grid consistent with govuk-frontend

---

packages/storybook/.storybook/config.js

Link logo to govuk-react repo

---

.eslintrc.js
API.md
CONTRIBUTING.md
components/main/src/index.js
components/page/package.json
components/page/src/atoms/main.js
components/page/src/atoms/width-container.js
components/page/src/fixtures.js
components/page/src/index.js
components/page/src/stories.js
components/page/src/test.js
components/panel/src/index.js
components/select/src/stories.js
components/top-nav/package.json
components/top-nav/src/__snapshots__/test.js.snap
components/top-nav/src/index.js
packages/constants/src/index.js
packages/govuk-react/package.json
packages/govuk-react/src/index.js
scripts/createComponent.js

Fixes #426 
**Checklist**:
Further stories and tests in new ticket to be followed up in #456

Page Component

---

components/grid-col/src/__snapshots__/test.js.snap
components/grid-col/src/index.js
components/grid-row/src/__snapshots__/test.js.snap
components/grid-row/src/index.js

* Remove margin-bottom from both grid-row and grid-col as per:
https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/_grid_layout.scss#L66
https://github.com/alphagov/govuk_frontend_toolkit/blob/master/stylesheets/_grid_layout.scss#L93
**Checklist**:

Remove margin-bottom from grid components

---

components/date-field/package.json
components/date-field/src/__snapshots__/test.js.snap
components/date-field/src/input.js
components/error-summary/src/__snapshots__/test.js.snap
components/input-field/src/__snapshots__/test.js.snap
components/input/package.json
components/input/src/__snapshots__/test.js.snap
components/input/src/index.js
packages/constants/src/focus.js
packages/constants/src/index.js
packages/constants/src/spacing.js

* `spacing` constants gains `SPACING_POINTS`
- provides lookup to match govuk-frontend
* `focus` file added to constants package
- adds `FOCUSABLE` style
* `Input` updated to match govuk-frontend styling
- uses `typography` from `@govuk-react/lib`
- exports raw `StyledInput` without withWhitespace
* `DateField` updated
- uses `StyledInput` from `Input`
**Checklist**:

Update styling of Input to match govuk-frontend

---

API.md
components/checkbox/README.md
components/radio/README.md

Docs for `Checkbox` and `Radio` updated
**Checklist**:

Documentation updates

---

API.md
components/checkbox/package.json
components/checkbox/src/__snapshots__/test.js.snap
components/checkbox/src/index.js
components/error-summary/src/__snapshots__/test.js.snap
components/hint-text/package.json
components/hint-text/src/__snapshots__/test.js.snap
components/hint-text/src/index.js
components/lead-paragraph/README.md
components/multi-choice/src/__snapshots__/test.js.snap
components/radio/package.json
components/radio/src/__snapshots__/test.js.snap
components/radio/src/index.js
components/select/src/__snapshots__/test.js.snap
components/text-area/src/__snapshots__/test.js.snap
packages/constants/src/focus.js

Updates to be more consistent with govuk-frontend
* HintText, Checkbox, Radio and LeadParagraph updated
**Checklist**:

Typography updates

---

ACCESSIBILITY.md

Accessibility statement

---

components/table/README.md
components/table/src/index.js

update link to table component

---

API.md
components/button/README.md
components/button/package.json
components/button/src/__snapshots__/test.js.snap
components/button/src/index.js

Button changed to use new spacing lib
**Checklist**:

Make Button component use new spacing

---

components/button/src/fixtures.js
components/button/src/stories.js

Add storybook example with button as router link

---

.travis.yml
package.json
scripts/travisPublish.sh
yarn.lock

fix npm publishing/release scripts

---

.travis.yml

attempt to fix .travis.yml release script

---

.travis.yml

change LERNA_ROOT_PATH to TRAVIS_BUILD_DIR in travis.yml as we're having issues with LERNA_ROOT_PATH and TRAVIS_BUILD_DIR should resolve to the same thing

TRAVIS_BUILD_DIR

---

README.md

Update sanitize.css URL

---

README.md

Add link to spectrum chat

---

API.md
components/date-field/src/__snapshots__/test.js.snap
components/error-summary/src/__snapshots__/test.js.snap
components/file-upload/src/__snapshots__/test.js.snap
components/input-field/src/__snapshots__/test.js.snap
components/label/README.md
components/label/src/__snapshots__/test.js.snap
components/label/src/index.js
components/select/src/__snapshots__/test.js.snap
components/text-area/src/__snapshots__/test.js.snap

Add `error` prop to proptypes for Label

---

API.md
components/breadcrumb/README.md
components/breadcrumb/src/__snapshots__/test.js.snap
components/breadcrumb/src/atoms/link/index.js
components/breadcrumbs/README.md
components/breadcrumbs/package.json
components/breadcrumbs/src/__snapshots__/test.js.snap
components/breadcrumbs/src/atoms/link/index.js
components/breadcrumbs/src/atoms/link/test.js
components/breadcrumbs/src/index.js
components/breadcrumbs/src/stories.js
components/breadcrumbs/src/test.js
packages/govuk-react/package.json
packages/govuk-react/src/index.js
packages/storybook/package.json

This keeps old Breadcrumb for now and just deprecates it
Closes #579
**Checklist**:

Rename Breadcrumb to Breadcrumbs

---

API.md
components/fieldset/README.md
components/fieldset/package.json
components/fieldset/src/__snapshots__/test.js.snap
components/fieldset/src/atoms/legend/__snapshots__/test.js.snap
components/fieldset/src/atoms/legend/index.js
components/fieldset/src/atoms/legend/test.js
components/fieldset/src/index.js
components/fieldset/src/stories.js
components/fieldset/src/test.js
packages/govuk-react/package.json
packages/govuk-react/src/index.js
packages/storybook/package.json

Provides a `Fieldset` component, as per [govuk-frontend](https://design-system.service.gov.uk/components/fieldset/).
**Checklist**:

Add Fieldset component

---

API.md
components/error-summary/src/__snapshots__/test.js.snap
components/error-summary/src/index.js
components/heading/README.md
components/heading/src/__snapshots__/test.js.snap
components/heading/src/index.js
components/heading/src/presets.js
components/heading/src/stories.js
components/heading/src/test.js
components/loading-box/src/stories.js
components/related-items/README.md
components/related-items/src/__snapshots__/test.js.snap
components/related-items/src/index.js
components/related-items/src/stories.js
components/related-items/src/test.js

* deprecate the `level` prop, in favour of using `H1`-`H6`
- uses of prop removed
* support `as` prop
**Checklist**:

Simplify Heading component

---

API.md
components/form-group/README.md
components/form-group/package.json
components/form-group/src/__snapshots__/test.js.snap
components/form-group/src/index.js
components/form-group/src/stories.js
components/form-group/src/test.js
packages/constants/src/index.js
packages/govuk-react/package.json
packages/govuk-react/src/index.js
packages/storybook/package.json
scripts/createComponent.js

Also tweaks createComponent script to be more in line with current principles
**Checklist**:

Add in form-group component

---

API.md
components/error-summary/src/__snapshots__/test.js.snap
components/inset-text/src/__snapshots__/test.js.snap
components/paragraph/src/__snapshots__/test.js.snap
components/paragraph/src/index.js
components/skip-link/README.md
components/skip-link/package.json
components/skip-link/src/__snapshots__/test.js.snap
components/skip-link/src/index.js
components/skip-link/src/stories.js
components/skip-link/src/test.js
packages/govuk-react/package.json
packages/govuk-react/src/index.js
packages/storybook/package.json

Replicates skip-link from govuk-frontend.
**Checklist**:

Add skip-link component

---

packages/lib/src/test.js

Add basic export test for @govuk-react/lib

---

components/grid-row/package.json
components/grid-row/src/__snapshots__/test.js.snap
components/grid-row/src/index.js

so as to allow for easy adjusting of margins, especially mb
**Checklist**:

Add withWhiteSpace to grid-row

---

yarn.lock

Update yarn.lock after greenkeeper react-testing-library update

---

package.json
yarn.lock

Update flow-bin to the latest version

---

.github/workflows/ci.yml
package.json
packages/api-docs/package.json
yarn.lock

downgrade docgen and add ci check for yarn docs

---

API.md
components/details/src/index.js

Details docs

---

components/date-field/src/__snapshots__/test.js.snap
components/date-field/src/input.js

Remove type=number from date field

---

API.md
components/search-box/src/__snapshots__/test.js.snap
components/search-box/src/index.js
components/search-box/src/stories.js
components/search-box/src/test.js
components/top-nav/src/index.js
components/top-nav/src/stories.js
packages/hoc/src/withWhiteSpace/stories.js

Support value= and onClick= with SearchBox

---

components/button/src/index.js
components/error-summary/src/__snapshots__/test.js.snap
components/file-upload/src/stories.js
components/footer/src/__snapshots__/test.js.snap
components/input-field/src/stories.js
components/link/src/__snapshots__/test.js.snap
components/link/src/index.js
components/ordered-list/src/__snapshots__/test.js.snap
components/radio/src/stories.js
components/related-items/src/__snapshots__/test.js.snap
components/tabs/src/fixtures.js
components/top-nav/src/__snapshots__/test.js.snap
components/top-nav/src/index.js
components/unordered-list/src/__snapshots__/test.js.snap
components/visually-hidden/src/__snapshots__/test.js.snap
components/visually-hidden/src/index.js

Fix console warnings

---

.gitignore
packages/govuk-react/package.json

copy govuk-react readme for npm

---

components/loading-box/src/index.js

Fix loading box fade

---

jsconfig.json

Go to Definition in vscode

---

.github/workflows/release-tags.yml

https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable

Fix GitHub release

---

jest.config.js
package.json
packages/example-application/package.json
packages/example-application/src/form.js
packages/example-application/src/home.js
packages/example-application/src/index.js
packages/example-application/src/stories.js
packages/govuk-react/src/index.js
packages/storybook/.storybook/main.js
yarn.lock

An example application for the purpose of:
- Reviewing API in situ
- Visual regression testing
- Integration testing
- Measuring code coverage of integration tests
When it comes to visual regression, the plan would be for different pages or application states to be preloaded in to their own story.
Closes #815
Fixes #119

Example application

---

components/date-field/src/index.js

Fixes #289
More work will follow in #249 and #164.

Allow Date Input and Container to be used standalone

---

API.md
components/global-style/README.md
components/global-style/src/index.js

Docs for GlobalStyles

---

jest.config.js
package.json
packages/example-application/cypress/plugins/index.js
packages/example-application/package.json
packages/storybook/.storybook/main.js
yarn.lock

See #848
https://github.com/penx/workspace-alias

Use workspace-alias instead of lerna-alias

---

README.md

Add example uses and request for maintainers and sponsors to readme.

Docs: Usage examples and sponsoring

---

CONTRIBUTING.md

Docs: Details on release notes

---

components/footer/src/index.tsx
packages/example-application/src/form.tsx
packages/example-application/src/index.tsx
packages/example-application/src/stories.tsx
packages/storybook/.storybook/main.js

Fixes #873
This is a non final form example.
I think we need a second page - the same form but using final form, this will be addressed in  #881

Add all form components to example application

---

packages/example-application/package.json
packages/example-application/src/final-form.tsx
packages/example-application/src/form.tsx
packages/example-application/src/index.spec.tsx
packages/example-application/src/index.tsx
packages/example-application/src/stories.tsx

Add Final Form example and Cypress tests

---

packages/example-application/package.json
packages/example-application/src/final-form.tsx
packages/example-application/src/form.tsx
packages/example-application/src/formik.tsx
packages/example-application/src/index.spec.tsx
packages/example-application/src/index.tsx
packages/example-application/src/stories.tsx
yarn.lock

Add Formik to example application

---

.gitignore

Add `.idea/` to git ignore list
(`./idea` folder is where Jetbrains IDE's add their config files)
This is so Jetbrains users don't commit their project settings

Add Jetbrains config to ignore

---

packages/example-application/package.json
packages/example-application/src/final-form.tsx
packages/example-application/src/form.tsx
packages/example-application/src/formik.tsx
packages/example-application/src/index.spec.tsx
packages/example-application/src/index.tsx
packages/example-application/src/react-hook-form.tsx
packages/example-application/src/stories.tsx
yarn.lock

Add react-hook-form to example application

---

packages/example-application/src/cypress/forms.spec.tsx
packages/example-application/src/forms/final-form.tsx
packages/example-application/src/forms/formik.tsx
packages/example-application/src/forms/react-hook-form.tsx

Make example forms only validate on submit

---

components/file-upload/src/index.tsx
components/label-text/src/__snapshots__/test.tsx.snap
components/label-text/src/index.tsx
components/label-text/src/test.tsx

LabelText should not be bold on error

---

README.md

Why is this a monorepo in readme

---

packages/example-application/package.json
packages/example-application/src/cypress/forms.spec.tsx
packages/example-application/src/forms/components/results.tsx
packages/example-application/src/forms/final-form.tsx
packages/example-application/src/forms/form.tsx
packages/example-application/src/forms/formik.tsx
packages/example-application/src/forms/forms.tsx
packages/example-application/src/forms/react-hook-form.tsx
packages/example-application/src/forms/react-jsonschema-form-helpers.jsx
packages/example-application/src/forms/react-jsonschema-form.tsx
packages/example-application/src/forms/validators/validators.tsx
packages/example-application/src/stories.tsx
yarn.lock

Fixes  #894
See
https://5ad61aab7f00090020dfdba8-jghgqgzfsd.chromatic.com/?path=/story/example-application--react-json-schema-form

react-jsonschema-form example

---

packages/lib/src/spacing/index.tsx
packages/lib/src/spacing/test.tsx
packages/lib/src/typography/index.tsx
packages/lib/src/typography/test.tsx
tsconfig.json

Fix ts issues on lib

---

packages/api-docs/src/markdown/generateDescription.tsx

Fix ts issues in api-docs

---

packages/hoc/src/test.tsx

Fix ts issues with hocs

---

packages/storybook-components/src/final-form-wrapper.tsx

Fix ts issues with storybook components

Fix ts issues with storybook components

---

.eslintrc.js
API.md
components/caption/README.md
components/caption/src/index.tsx
components/details/src/index.tsx
components/document-footer-metadata/src/index.tsx
components/error-summary/README.md
components/error-summary/src/index.tsx
components/heading/src/heading.tsx
components/ordered-list/README.md
components/ordered-list/src/index.tsx
components/unordered-list/README.md
components/unordered-list/src/index.tsx
jest.config.js
package.json
packages/lib/src/index.tsx
packages/lib/src/spacing/index.tsx
packages/lib/src/typography/index.tsx
tsconfig.json

- use @typescript-eslint/parser for eslint
- fixes/improvements to tsconfig.json, 
- fix ts issues on
- backlink 
- caption
- details
- document-footer-metadata
- error-summary (issues remain on fixtures due to InputField and TextArea)
- heading
- ordered-list
- unordered-list
These files still have issues:
- components/button/src/index.tsx
- components/checkbox/src/index.tsx
- components/date-field/src/index.tsx
- components/date-field/src/input.tsx
- components/error-summary/src/fixtures.tsx
- components/error-text/src/stories.tsx
- components/fieldset/src/atoms/legend/test.tsx
- components/file-upload/src/index.tsx
- components/footer/src/fixtures.tsx
- components/form-group/src/stories.tsx
- components/grid-col/src/index.tsx
- components/input/src/index.tsx
- …

Fix some component TS issues

---

components/error-text/src/stories.tsx
components/fieldset/src/atoms/legend/index.tsx
components/footer/src/index.tsx
components/footer/src/pngimport.d.ts
components/label/src/__snapshots__/test.tsx.snap
components/label/src/test.tsx
components/link/src/index.tsx
components/list-navigation/src/index.tsx
components/loading-box/src/index.tsx
components/main/src/index.tsx
components/panel/src/index.tsx
components/table/src/index.tsx
components/tag/src/test.tsx
packages/lib/src/spacing/index.tsx

Follow up to #951
Fix TS issues with:
- ErrorText
- FieldsetLegend
- Footer
- Gridcol
- Label
- Link
- ListNavigation
- LoadingBox
- Main
- Panel
- Table
- Tag
There are still issues with:
- components/button
- components/checkbox
- components/date-field
- components/error-summary
- components/file-upload
- components/form-group
- components/input-field
- components/input
- components/loading-box (due to form fields in stories)
- components/multi-choice
- components/radio
- components/search-box
- components/select
- components/skip-link
- components/tabs
- components/text-area
- components/top-nav
- components/visually-hidden
- packages/example-application
- packages/storybook-components

Fix more TS issues on components

---

components/input/src/index.tsx

Fix TS issues with Input

---

components/checkbox/src/index.tsx
components/checkbox/src/stories.tsx
components/radio/src/index.tsx
components/radio/src/stories.tsx

Fix TS issues on radio and checkbox, part of #901

Fix TS issues on radio and checkbox

---

.eslintrc.js
API.md
components/date-field/README.md
components/date-field/src/__snapshots__/test.tsx.snap
components/date-field/src/index.tsx
components/date-field/src/input.tsx
components/date-field/src/stories.tsx
components/date-field/src/test.tsx
components/input/README.md
components/label-text/README.md
components/label-text/src/index.tsx
components/link/README.md
components/list-navigation/README.md
components/loading-box/README.md
components/main/README.md
components/panel/README.md
components/table/README.md
components/tabs/src/fixtures.tsx
components/top-nav/src/index.tsx

Fix TS issues with DateField, part of #901

Fix TS issues with DateField

---

components/file-upload/README.md
components/file-upload/src/index.tsx

Fix TS issues with FileUpload, part of #901

Fix TS issues with FileUpload

---

components/input-field/src/index.tsx
components/input-field/src/stories.tsx

Fix TS issues with InputField, part of #901

Fix TS issues with InputField

---

components/multi-choice/src/__snapshots__/test.tsx.snap
components/multi-choice/src/index.tsx
components/multi-choice/src/test.tsx

Fix TS issues with MultiChoice, part of #901

Fix TS issues with MultiChoice

---

components/search-box/src/index.tsx

Fix TS issues with SearchBox, part of #901

Fix TS issues with SearchBox

---

components/select/src/index.tsx
components/select/src/stories.tsx

Fix TS issues with Select, part of #901

Fix TS issues with Select

---

components/tabs/src/atoms/tab/index.tsx
components/tabs/src/fixtures.tsx

Fix TS issues with Tabs, part of #901

Fix TS issues with Tabs

---

components/skip-link/src/stories.tsx

Fix TS issues with SkipLink, part of [#901](https://github.com/govuk-react/govuk-react/issues/901)

Fix TS issues with SkipLink

---

components/text-area/src/__snapshots__/test.tsx.snap
components/text-area/src/index.tsx
components/text-area/src/test.tsx

Fix TS issues on TextArea, part of #901

Fix TS issues on TextArea

---

components/visually-hidden/src/stories.tsx

Fix TS issues with VisuallyHidden, part of #901

Fix TS issues with VisuallyHidden

---

components/top-nav/src/__snapshots__/test.tsx.snap
components/top-nav/src/index.tsx
components/top-nav/src/stories.tsx
components/top-nav/src/test.tsx

Fix TS issues with TopNav, part of #901

Fix TS issues with TopNav

---

components/error-summary/src/fixtures.tsx
components/error-summary/src/index.tsx
components/input-field/src/index.tsx
components/text-area/src/index.tsx
components/text-area/src/stories.tsx

Fix TS issues with ErrorSummary, fix TextArea, update some docs. Part of [#901](https://github.com/govuk-react/govuk-react/issues/901)

Fix TS issues with ErrorSummary, fix TextArea, update some docs

---

API.md
components/button/README.md
components/button/src/index.tsx
components/checkbox/README.md
components/error-summary/README.md
components/input-field/README.md
components/link/src/index.tsx
components/multi-choice/README.md
components/pagination/src/anchor.tsx
components/radio/README.md
components/select/README.md
components/tabs/src/atoms/tab/index.tsx
components/text-area/README.md
components/top-nav/README.md

Fix TS issues with Button, part of #901

Fix TS issues with Button

---

.eslintrc.js
components/caption/src/test.tsx
components/fieldset/src/atoms/legend/test.tsx
components/heading/src/test.tsx
components/tabs/src/fixtures.tsx
components/top-nav/src/atoms/menu-button/index.tsx
package.json
packages/api-docs/src/index.tsx
packages/example-application/src/cypress/forms.spec.tsx
packages/example-application/src/cypress/tsconfig.json
tsconfig.json
yarn.lock

Part of #952
Next step is to reenable the 2 disabled rules.

Enable ts-lint and fix issues

---

.eslintrc.js
components/error-text/src/index.tsx
components/file-upload/src/index.tsx
components/footer/src/pngimport.d.ts
components/input-field/src/index.tsx
components/multi-choice/src/index.tsx
components/radio/src/stories.tsx
components/select/src/index.tsx
components/text-area/src/index.tsx
package-lock.json
packages/example-application/package.json
packages/example-application/src/forms/final-form.tsx
packages/example-application/src/forms/formik.tsx
packages/example-application/src/forms/react-jsonschema-form-helpers.tsx
packages/example-application/src/forms/validators/validators.tsx
packages/lib/src/link/index.tsx
packages/lib/src/spacing/index.tsx
packages/lib/src/typography/index.tsx

Fix all no-explicit-any warnings

---

components/date-field/src/index.tsx
components/date-field/src/input.tsx
components/error-summary/src/index.tsx
packages/example-application/src/forms/components/results.tsx

Remove use of ...args in function types

---

README.md

Add @types/styled-components to recommended install

---

README.md
packages/storybook/.storybook/preview.js

- Prioritise publishing components over backlog and elements
- Fix default story

Fix default story, Prioritise publishing components

---

README.md

Add DEFRA to known users

---

.github/workflows/chromatic.yml
packages/storybook/package.json
yarn.lock

Enable Chromatic Turbosnap

---

CONTRIBUTING.md

Explain docs command in CONTRIBUTING.md

---

.github/dependabot.yml

Change dependabot interval and limit

---

.github/workflows/dependabot-yarn.yml

As per https://blog.alphasmanifesto.com/2021/11/07/yarn-2-dependabot/

Yarn 2 support for dependabot

---

packages/api-docs/package.json
yarn.lock

I think jimp was a dependency of component-image, which we no longer use

Remove jimp dependency

---

components/top-nav/package.json
yarn.lock

...to remove prop-types dependency

icon-crown update

---

components/button/src/index.tsx
components/date-field/src/input.tsx
components/details/src/index.tsx
components/document-footer-metadata/src/index.tsx
components/error-summary/src/index.tsx
components/fieldset/src/atoms/legend/index.tsx
components/fieldset/src/index.tsx
components/footer/src/index.tsx
components/heading/src/heading.tsx
components/label/src/index.tsx
components/loading-box/src/index.tsx
components/main/src/index.tsx
components/multi-choice/src/index.tsx
components/pagination/src/anchor.tsx
components/pagination/src/index.tsx
components/panel/src/index.tsx
components/phase-banner/src/index.tsx
components/section-break/src/index.tsx
components/table/src/index.tsx
components/tabs/src/index.tsx
components/top-nav/src/index.tsx
components/unordered-list/src/index.tsx
components/warning-text/src/index.tsx

Raised to address #1644
**Checklist**:

Typings for `...props` on components
