govuk-react/govuk-react

.travis.yml

skip cleanup for npm deploys as node_modules folder is needed to execute publish

npm deploy fix

---

components/breadcrumb/src/__snapshots__/test.js.snap
components/breadcrumb/src/stories.js
components/breadcrumb/src/test.js

Fixes #97 
- added examples to show the current page (not being a link)

added example of last breadcrumb being not a link

---

components/phase-banner/package.json
components/phase-banner/src/__snapshots__/test.js.snap
components/phase-banner/src/index.js

Adjusts phase-banner so it has a `margin-top: 10px` matching GDS.
Also changes it to use a `div` rather than a `p` tag, as this helps simplify styling and removes a styling oddity (`p` elements have a `-webkit-margin-before` and `-webkit-margin-after` set in user-agent stylesheet).
**Checklist**:

Tweak phase-banner styling

---

components/breadcrumb/src/index.js
components/breadcrumb/src/stories.js
components/breadcrumb/src/test.js
components/list-navigation/src/index.js
components/ordered-list/src/index.js
components/unordered-list/src/index.js
yarn.lock

fixes #123 
When the breadcrumb was being passed in as null/empty array it was showing a "ghost" breadcrumb
*before:*
*after:*

Fix for duff breadcrumb children

---

package.json
packages/api-docs/package.json

Remove version numbers from root package.json, so that outdated version references are not left behind after a `lerna publish`, see:
https://github.com/lerna/lerna/issues/1335

remove version numbers from root package.json

---

components/breadcrumb/src/index.js
components/breadcrumb/src/test.js
components/related-items/package.json

Allow attributes to be set on Breadcrumbs

---

scripts/release.sh

lerna uses tags to determine what has changed, we need to make sure we have all tags locally
see https://github.com/lerna/lerna/issues/1345

Get all tags before running lerna publish

---

.travis.yml

CI/Travis update - Only publish packed releases that match the current Lerna version to GitHub releases.

only publish current version to github

---

components/select/src/index.js
components/select/src/stories.js

- export select-input as its own module
- show example of using a select inline with a label
this is the existing design of the dropdown (excluding the red rect.) which shows a label inline to a select dropdown. The dropdown needs to be shown in the GDS styling

enhance dropdown (878)

---

packages/govuk-react/package.json
packages/govuk-react/src/index.js

We don't want a parent project to raise a snyk vulnerability when importing govuk-react.
Though the issues are not relevant, the storybook isn't really a required dependency, so removing this workaround for now.

remove snyk vulnerability

---

packages/hoc/src/asAnchor/test.js
packages/hoc/src/asPaginationItem/test.js
packages/hoc/src/withWhiteSpace/test.js

Some uses of `toBeTruthy` in tests were incorrect - this fixes them.
**Checklist**:

Fix uses of toBeTruthy in tests

---

components/back-link/README.md
components/breadcrumb/README.md
components/button/README.md
components/checkbox/README.md
components/date-input/README.md
components/document-footer-metadata/README.md
components/file-upload/README.md
components/grid-row/README.md
components/header/README.md
components/hidden-text/README.md
components/input-field/README.md
components/input/README.md
components/inset-text/README.md
components/list-navigation/README.md
components/loading-box/README.md
components/multi-choice/README.md
components/ordered-list/README.md
components/panel/README.md
components/paragraph/README.md
components/phase-banner/README.md
components/radio/README.md
components/search-box/README.md
components/select/README.md
components/table/README.md
components/text-area/README.md
components/top-nav/README.md
components/unordered-list/README.md
packages/api-docs/src/markdown/generateProp.js
packages/api-docs/src/markdown/generatePropDefaultValue.js

Markdown tables don’t support multiline cells, meaning defaultTypes such as objects, that were returned on multiple lines would break our auto-generated readme docs. This change removes line-returns and carriage-returns from defaultProp values ensuring `objects` render on one line and in our documentation. yey!
This change also wraps rendered defaultProps in markdown code comments.

Allow defaultProp `objects` render in api-docs

---

components/back-link/src/__snapshots__/test.js.snap
components/back-link/src/index.js

fixes #334 
added `backgroundColor: transparent` to Backlink button because it was showing as grey in Safari on MacOS.

added fix for backlink bgcolor and updated snapshot

---

components/file-upload/src/index.js
components/input-field/src/index.js
components/multi-choice/src/index.js
components/select/src/index.js
components/text-area/src/index.js

Fixes console errors on form elements, should be `PropTypes.any` https://github.com/final-form/final-form#initial-any
Example of error: https://codesandbox.io/s/nwmy8k3xrl
**Checklist**:

fix meta.initial proptype for forms

---

components/supporting-header/README.md
components/supporting-header/package.json
components/supporting-header/src/__snapshots__/test.js.snap
components/supporting-header/src/fixtures.js
components/supporting-header/src/index.js
components/supporting-header/src/stories.js
components/supporting-header/src/test.js
package.json
packages/govuk-react/package.json
packages/govuk-react/src/index.js
packages/storybook/package.json

Component for rendering supporting header text. Closes #99 and #328.
Despite the discussion on #99 this is a separate component, and thus can be used alongside headings or by itself.
Screenshots of stories;

Supporting Header Component

---

components/loading-box/src/__snapshots__/test.js.snap
components/loading-box/src/index.js
components/loading-box/src/stories.js

**Checklist**:
Solution: Apply more sensible min-height of 10px as a fall back so at least the spinner will be displayed.
closes #381

Apply more sensible minHeight value of '10px' as a fallback

---

components/hidden-text/src/__snapshots__/test.js.snap
components/hidden-text/src/index.js

Having replicated #339 in Firefox (Mac) locally, this is a proposed fix - simply removing the display statement - but of course this will only be acceptable if it doesn't have any adverse effects where the component is used.
**Checklist**:

Proposed fix for #339

---

components/table/src/__snapshots__/test.js.snap
components/table/src/atoms/Cell/index.js

Fixes #414 
This PR adds `break-word` to table cells to ensure table cells to not render larger than their intended size.
It has been mentioned that this adjustment deviates from GDS, as the table cells there do no specify `break-word`, I am assuming this is because this issue has not been experienced by any of their implementations, or if it has, it has been overridden during its implementation.
Before;
After;

Add break-word to table cells

---

components/error-summary/src/test.js

Bring error-summary test coverage to 100%

---

components/date-field/README.md

Changed DateInput to DateField. Very minor but just spotted as I was reading through.
**Checklist**:

Fix typo in date-field README.md

---

API.md
components/date-field/README.md
components/date-field/src/index.js
components/error-summary/src/__snapshots__/test.js.snap
components/header/README.md
components/header/package.json
components/header/src/__snapshots__/test.js.snap
components/header/src/index.js
components/header/src/stories.js
components/header/src/test.js
components/panel/README.md
components/related-items/src/__snapshots__/test.js.snap
components/top-nav/README.md
components/top-nav/package.json
components/top-nav/src/__snapshots__/test.js.snap
components/top-nav/src/index.js
components/top-nav/src/stories.js
packages/api-docs/src/markdown/generateProp.js
packages/api-docs/src/markdown/generatePropDescription.js
packages/api-docs/src/markdown/generatePropType.js
packages/constants/src/index.js
packages/constants/src/spacing.js
packages/constants/src/typography.js
packages/lib/package.json
packages/lib/src/index.js
packages/lib/src/typography.js
packages/lib/src/typography/index.js
packages/lib/src/typography/test.js

Add @govuk/lib package which implements a preliminary `typography` lib, aiming to replicate typography utilities from govuk-frontend sass
* used in header component
TODO: Use typography lib throughout govuk-react for font sizes
**Checklist**:

Improve typography in govuk-react to more closely match govuk-frontend

---

scripts/chromatic.sh

CI bugfix - don't auto accept changes from external PRs.
This resolves the CI issue we had on https://github.com/govuk-react/govuk-react/pull/497
@jsrobertson 
> TRAVIS_BRANCH:
for builds triggered by a pull request this is the name of the branch targeted by the pull request.
https://docs.travis-ci.com/user/environment-variables/#default-environment-variables

CI bugfix - don't auto accept changes from external PRs

---

API.md
components/button/README.md
components/button/package.json
components/button/src/__snapshots__/test.js.snap
components/button/src/fixtures.js
components/button/src/index.js
components/button/src/stories.js
packages/hoc/src/withWhiteSpace/index.js
yarn.lock

`Button` component now styled more consistently with govuk-frontend
Supports following additional new props:
* `buttonColour` to override default button colour
* `buttonHoverColour` which defaults to `buttonColour` darkened by 5%
* `buttonShadowColour` which defaults to `buttonColour` darkened by 15%
* `buttonTextColour` which defaults to govuk white
TODO:
`withWhiteSpace` HOC does not yet support `adjustment` value, which `Button` now attempts to use, so this needs to be added - however that can be done in a later PR
**Checklist**:

Update Button styling

---

components/button/src/__snapshots__/test.js.snap
components/button/src/index.js

Ensure our (default) button shadow colour exactly matches govuk-frontend
(using `darken(0.15, buttonColour)` from polished is producing a colour with a value that's 1 darker in the green channel vs govuk-frontend's sass `darken($govuk-button-colour, 15%)`)
**Checklist**:

Button shadow colour tweak

---

packages/lib/src/index.js
packages/lib/src/spacing/index.js
packages/lib/src/spacing/test.js

New spacing lib added
* `simple` returns simple spacing value
* `responsive` returns a responsive styles for params
- based based off govuk-frontend but adds support for array of directions
* `responsiveMargin` convenience wrapper
- calls `responsive` setting `property` to `margin`
* `responsivePadding` convenience wrapper
- calls `responsive` setting `property` to `padding`
**Checklist**:

Add new spacing lib

---

components/error-summary/src/__snapshots__/test.js.snap
components/input-field/src/__snapshots__/test.js.snap
components/input-field/src/index.js
packages/hoc/package.json
packages/hoc/src/withWhiteSpace/__snapshots__/test.js.snap
packages/hoc/src/withWhiteSpace/index.js
packages/hoc/src/withWhiteSpace/stories.js
packages/hoc/src/withWhiteSpace/test.js
packages/lib/src/spacing/index.js
packages/lib/src/spacing/test.js

* `withWhiteSpace` HOC updated
- supports `margin` and `padding` props and config
- values can be:
- single number (size to use in all directions)
- object in format `{ size, direction, adjustment }` (as per `responsivePadding` etc lib call)
- array of numbers/objects
- `mb`/`marginBottom` still supported for backward compatibility
- example stories cleaned up
- no need to double-wrap `withWhiteSpace`
- examples for new options added against a demo component
* `spacing` lib enhanced
- styles no longer set as `px` strings, as emotion does that automatically
- `responsiveMargin` and `responsivePadding` now support single integer size value
* fix: `InputField` no longer double-wraps `withWhiteSpace`
**Checklist**:

Enhanced withWhiteSpace HOC

---

CONTRIBUTING.md
package.json
packages/hoc/src/withWhiteSpace/index.js
packages/lib/src/spacing/index.js
packages/lib/src/spacing/test.js

* adds new `withWhiteSpace` function to spacing lib
- generates spacing styles, accepting `margin`, `padding` and `mb` props
- intended for use within styled component definitions
`withWhiteSpace` HOC refactored to use function, but is now deprecated
Aims to provide a solution to #522
**Checklist**:

Add `withWhiteSpace` to spacing lib

---

API.md
components/table/README.md
components/table/package.json
components/table/src/__snapshots__/test.js.snap
components/table/src/atoms/Caption/index.js
components/table/src/atoms/Cell/index.js
components/table/src/atoms/Cell/test.js
components/table/src/atoms/CellHeader/index.js
components/table/src/atoms/Row/index.js
components/table/src/atoms/TableBody/index.js
components/table/src/atoms/TableHeader/index.js
components/table/src/fixtures.js
components/table/src/index.js
components/table/src/stories.js
components/table/src/test.js
packages/constants/src/index.js

* Styling updated to match govuk-frontend
* Options/props now better match govuk-frontend
* Docs updated
* Now uses fixtures
* Bug fixed in NTA_LIGHT_TABULAR const definition
**Checklist**:

Update Table component to match govuk-frontend

---

API.md
components/caption/README.md
components/caption/package.json
components/caption/src/__snapshots__/test.js.snap
components/caption/src/fixtures.js
components/caption/src/index.js
components/caption/src/stories.js
components/caption/src/test.js
packages/govuk-react/package.json
packages/govuk-react/src/index.js
packages/storybook/package.json

Caption component added, as per govuk-frontend typography
Works in a similar manner to `Header`, accepting a `size` prop that's either a string or numeric fitting in the GDS font scale list
**Checklist**:

Add new Caption component

---

API.md
components/grid-col/README.md
components/grid-col/package.json
components/grid-col/src/__snapshots__/test.js.snap
components/grid-col/src/index.js
components/grid-col/src/stories.js
components/grid-col/src/test.js
components/table/README.md
components/table/src/__snapshots__/test.js.snap
components/table/src/atoms/Cell/index.js
components/table/src/fixtures.js
components/table/src/index.js
components/table/src/stories.js
components/table/src/test.js
packages/constants/src/index.js
packages/constants/src/spacing.js
packages/lib/src/spacing/index.js
packages/lib/src/spacing/test.js

* `WIDTHS` constant object added
* `withWidth` added to spacing lib
- produces a responsive width style
- 100% width, with specified width for tablet or greater
- no style if no config/prop provided
- accepts a `width` config value
- accepts a `setWidth` prop
- config/prop accepts key from `WIDTHS` config, or any value
- config also supports `mediaQuery` (to pick a different query) and `noDefault` (to omit 100% width)
* `Table.Cell` now uses `withWidth`
- `Table` examples and docs updated to demo use
* `GridCol` updated
- `columnThreeQuarters` and `columnFull` added
- `column*` props however now deprecated in favour of...
- `setWidth` prop, provided with the aid of `spacing.withWidth`
- `setDesktopWidth` prop allows desktop breakpoints for column widths
**Checklist**:

Width settings

---

API.md
components/button/src/__snapshots__/test.js.snap
components/button/src/index.js
components/visually-hidden/README.md
components/visually-hidden/package.json
components/visually-hidden/src/__snapshots__/test.js.snap
components/visually-hidden/src/index.js
components/visually-hidden/src/stories.js
components/visually-hidden/src/test.js
packages/govuk-react/package.json
packages/govuk-react/src/index.js
packages/lib/src/index.js
packages/lib/src/visually-hidden/index.js
packages/lib/src/visually-hidden/test.js
packages/storybook/package.json
yarn.lock

adds new `VisuallyHidden` component, which styles a span as visually-hidden replicating the most common use of that class within govuk-frontend
adds `visuallyHidden()` and `visuallyHidden.focusable()` to `@govuk-react/lib`, tracking equivalent sass helper in govuk-frontend
**Checklist**:

Add VisuallyHidden component and lib

---

packages/storybook-components/src/WithDocsCustom.js

withDocsCustom's stylings can be useful regardless of where the example stories have a readme or not, providing an empty string as a default parameter allows the function to be called with no parameters
**Checklist**:

Default parameter for withDocsCustom

---

components/caption/src/stories.js

Two example stories for caption have had their knobs changed to you the select addon but crucially, the component default is unchanged
**Checklist**:

Introduce select storybook addon for caption

---

components/tabs/src/__snapshots__/test.js.snap
components/tabs/src/atoms/list/index.js
components/tabs/src/atoms/panel/index.js
components/tabs/src/atoms/tab/index.js
components/tabs/src/index.js

Some styling calls weren't being made correctly, so their styles were not being applied
Use `BORDER_COLOUR`
Tweak of tab item `:before` `content` as per recent govuk-frontend fix
**Checklist**:

Minor tab styling tweaks and fixes

---

package.json
yarn.lock

Failed to update babel-jest to v24 with the other jest modules. I was under the impression that it was wrapped up inside jest v24. I now think [otherwise](https://jestjs.io/docs/en/getting-started#using-babel)
**Checklist**:

Updating babel-jest inline with other jest modules

---

components/error-summary/src/index.js
components/error-summary/src/test.js

GDS guidelines on https://design-system.service.gov.uk/components/error-summary/ states that the heading must be ‘There is a problem’:
We should therefore default the heading to this value.
I haven't changed the docs for the component, since we do still allow the override.  Was thinking about something like:
>Optional message to alert the user to a problem goes here, defaulting to 'There is a problem'

Default error summary heading to match GDS guidelines

---

jest.config.js
package.json

clearMocks has been added, testEnvironment has been set to jsdom so that --env=jsdom is not needed to be declared in the npm scripts.
**Checklist**:

Change to jest.config.js

---

components/error-summary/src/__snapshots__/test.js.snap
components/error-summary/src/index.js

GDS uses 24px for the error summary heading - see https://design-system.service.gov.uk/components/error-summary/.  At present error summary uses `H2` which brings in size `LARGE` of 36px instead.  This change reduces the size to `MEDIUM` which matches the GDS design.
Storybook pre change:
Storybook post change:
GDS Error Summary page:
Note that the font size reduction was originally attempted in https://github.com/govuk-react/govuk-react/pull/634 by switching from `H2` to `H3`, but I have subsequently discovered (thanks @jsrobertson) that a `size` can be applied to a heading element so have done that instead.

Reduce error summary heading size to match GDS

---

API.md
components/error-summary/README.md
components/page/README.md
components/page/package.json
components/page/src/index.js
components/skip-link/README.md
components/skip-link/src/__snapshots__/test.js.snap
components/skip-link/src/index.js

`Page` now includes a `SkipLink`, and will accept an `id` which will be applied to the `main` page contents wrapper.
`SkipLink` now defaults contents
Closes #600 
**Checklist**:

Add skip-link to page

---

packages/hoc/src/withWhiteSpace/stories.js
packages/lib/src/spacing/index.js
packages/lib/src/spacing/test.js

it's now possible to provide negative whitespace sizes
also fixes `withWhiteSpace` stories rendering in chromatic by wrapping story items in a `div` rather than `Fragment`
Addresses half of #610
**Checklist**:

Negative whitespace support

---

package.json

Lerna was updated when greenkeeper was installed - but should be kept on v2

revert lerna version

---

API.md
components/footer/README.md
components/footer/src/__snapshots__/test.js.snap
components/footer/src/atoms/licence/index.js
components/footer/src/atoms/link/index.js
components/footer/src/atoms/meta-item/index.js
components/footer/src/atoms/section-heading/index.js
components/footer/src/fixtures.js
components/footer/src/index.js
yarn.lock

- Fixed an incorrect type for `listColumns` which was shown and used in documentation causing a propType error in the console.
- Changed `<FooterLink>` to use `<LinkDocumented>` from `<Link>`.  This was causing issues with noVisitedState and textColour props getting passed down to the rendered dom element.
- `yarn.lock` also updated from previous commit related to the lerna version change in `package.json`
- Set Footer section headings to be a `h2`.  Not specified at the moment so are defaulting to `h1`.
- Added OGL Link to License information
- Fixed responsive issue with Meta content wrapping too soon.
**Checklist**:

Footer component updates

---

components/tabs/src/atoms/tab/index.js
components/tabs/src/atoms/title/index.js
components/tabs/src/fixtures.js
components/tabs/src/stories.js
package.json

Includes a storybook example
**Checklist**:

Allow tabs to be used with react-router

---

components/tabs/src/stories.js

I don't think it's doing anything and we don't do it anywhere else
Fixes #635

Remove WithDocsCustom from tabs examples

---

.github/workflows/chromatic.yml
packages/example-application/src/stories.js
packages/storybook/.storybook/preview.js

So that we can incrementally reenable Chromatic to get around usage issues

Disable Chromatic on everything other than ExampleApplication

---

components/back-link/src/index.js

Fixes:  #449
Revist: #1171
To match: https://github.com/alphagov/govuk-frontend/pull/1620
React Router would provide an href.
If no href is provided, the absense of an underline would be a prompt for the developer to add one.
This mirrors user agent stylesheets for an anchor.

Only underline backlink if it has an href

---

scripts/npmPublish.sh

e.g. if @govuk-react/images has not been bumped and is already published, don't report failure on ci

Don't return error if can't publish module

---

API.md
components/date-field/README.md
components/file-upload/README.md
components/input-field/src/__snapshots__/test.tsx.snap
components/input-field/src/index.tsx
components/search-box/src/__snapshots__/test.tsx.snap
components/search-box/src/index.tsx
packages/example-application/src/forms/react-hook-form.tsx

Fixes  #921
> components that take an input prop and spread it to the input, don't need forwardRef as it can be done via the input prop.
>
> I'll remove it for InputField, add it to SearchBox and not touch Select and TextArea
https://github.com/govuk-react/govuk-react/issues/921#issuecomment-913180653

Review use of forwardRef

---

.eslintrc.js
API.md
components/back-link/README.md
components/back-link/src/index.tsx
components/label/README.md
components/tabs/src/atoms/tab/index.tsx
components/tabs/src/fixtures.tsx
components/top-nav/src/atoms/menu-button/index.tsx
package.json
packages/api-docs/src/index.tsx
packages/example-application/src/forms/components/results.tsx

Fixes #952 (combined with #972)
Enabling this results in almost 400 warnings, but does fail on CI.
These warnings will be used as part of #949 at which point they should hopefully be drastically reduced and any remaining warnings can be tackled at that point if needed.

TypeScript: Enable explicit-module-boundary-types

---

packages/storybook/.storybook/manager.js

If your OS (such as macOS) is set to use the dark theme, some browsers (like Firefox) pass this through to Storybook which will then use the dark theme as default. This means components will then not have a white background when viewing them within Storybook.
This PR sets the base theme to be the `light` Storybook theme, regardless of what your OS setting is, as the components are meant to be placed on a white background.
Changed from:
To:
**Checklist**:

Set storybook to be based on light theme

---

package.json
yarn.lock

Fix Netlify errors by migrating to bundlesize2

---

components/radio/src/__snapshots__/test.tsx.snap
components/radio/src/index.tsx

**Checklist**:
**Motivation**:
Fixes #378. I'm not sure it was ever previously fixed - while the bug went away for most people, at different zoom levels browsers can render this weirdly and cause a white dot to appear in the center of the radio circle. In particular, I find this very reproducable in Chrome at 125% and 175% zoom levels. It's common for users with HiDPI displays for their browser to automatically scale things, e.g. phones and 4k displays, and therefore this bug is most prominent there.
Before:
After:

Fix radio button white-dot bug

---

scripts/npmPublish.sh

This did not cause the failure of the 0.10.2 but will clean up some noise in the logs

Fix prerelease script

---

components/heading/src/heading.tsx

Fix for https://github.com/govuk-react/govuk-react/issues/1138
Some thoughts:
- I tested this by temporarily upgrading the React type defs to v18 and then reverted as the upgrade to React 18 seemed like a fairly big job
- I don't know what other components will also have a missing `children` prop. I've only fixed headers.
- I don't know what an appropriate comment for the property would be
**Checklist**:

Add props for children to headers

---

components/document-footer-metadata/src/__snapshots__/test.tsx.snap
components/document-footer-metadata/src/index.tsx
components/search-box/src/__snapshots__/test.tsx.snap
components/warning-text/src/__snapshots__/test.tsx.snap
packages/icons/src/ArrowLeft/__snapshots__/test.tsx.snap
packages/icons/src/ArrowRight/__snapshots__/test.tsx.snap
packages/icons/src/ButtonArrow/__snapshots__/test.tsx.snap
packages/icons/src/IconImportant/__snapshots__/test.tsx.snap
packages/icons/src/SVGBase/__snapshots__/test.tsx.snap
packages/icons/src/SVGBase/index.tsx
packages/icons/src/Search/__snapshots__/test.tsx.snap
packages/icons/src/Spinner/__snapshots__/test.tsx.snap
packages/icons/src/Spinner/index.tsx

Hiya 👋 We're currently using `govuk-react` on a project with a strict [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP). The CSP directive [style-src](https://content-security-policy.com/style-src/) has been causing us some grief due to the fact that there were three instances (`Document Footer Metadata`, `Spinner` and `SVGBase`) of inline styling in this library.
I've replaced these inline styles with `styled-components` styling 💅 which you use everywhere else. There should be no change to the behaviour of any of the components, visual or interactive.
Thank you. Big fans of this library! 😄 💯 
**Checklist**:

Fix inline styling breaking CSPs

---

components/error-summary/src/index.tsx

A tab index greater than 0 violates the axe-core 4.4 tabindex rule.
See https://dequeuniversity.com/rules/axe/4.4/tabindex?application=AxeChrome
Looks like this was previously flagged in issue  https://github.com/govuk-react/govuk-react/issues/642 but never resolved.
**Checklist**:

accessibility: set StyledErrorText tabindex to 0
